version: "3.9"

services:
  service1:
    build: ./API
    container_name: fastapi_service_8000
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - app_network

  service2:
    build: ./app_rag
    container_name: fastapi_service_8001
    ports:
      - "8001:8001"
    environment:
      - ENV=production
    networks:
      - app_network

  streamlit:
    build: ./UI
    container_name: streamlit_service
    ports:
      - "8501:8501"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
